# Generated by Django 5.0.2 on 2024-02-16 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grando', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='Alumnos',
        ),
        migrations.RenameModel(
            old_name='Curso',
            new_name='Cursos',
        ),
        migrations.RenameModel(
            old_name='Entregable',
            new_name='Entregas',
        ),
        migrations.RenameModel(
            old_name='Profesor',
            new_name='Profesores',
        ),
    ]
