# Generated by Django 5.0.2 on 2024-03-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grando', '0002_rename_estudiante_alumnos_rename_curso_cursos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profesores',
            name='apellido',
            field=models.CharField(max_length=20),
        ),
    ]
