# Generated by Django 5.0.2 on 2024-03-08 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grando', '0003_alter_cursos_id_alter_profesores_apellido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='camada',
            new_name='cantidad',
        ),
    ]
