# Generated by Django 5.0.2 on 2024-03-08 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grando', '0004_rename_camada_cursos_cantidad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cursos',
            new_name='Bebida_blanca',
        ),
    ]
