# Generated by Django 5.0.2 on 2024-03-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grando', '0005_rename_cursos_bebida_blanca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vinos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Alumnos',
        ),
    ]
